apiVersion: v1
kind: Pod
spec:
  serviceAccountName: default
  hostAliases:
  - ip: 127.0.0.1
    hostnames:
    - kubernetes
  containers:
  - name: terraform
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    image: "hashicorp/terraform:latest"
    imagePullPolicy: Always
    command: [/bin/sh, -c, --]
    args: [while true; do sleep 30; done;]
    volumeMounts:
    - name: dockersocket
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock